# Generated by Django 5.2.11 on 2026-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
