# Generated by Django 5.2.11 on 2026-03-24 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_department_alter_profile_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subject'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
