# Generated by Django 5.2.11 on 2026-03-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_encoding_updated_at_profile_face_encoding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveattendancesession',
            name='kiosk_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
