# Generated by Django 5.2.11 on 2026-03-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subjectenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='division',
        ),
        migrations.AddField(
            model_name='subject',
            name='divisions',
            field=models.ManyToManyField(blank=True, related_name='regular_subjects', to='accounts.division'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semesters',
            field=models.ManyToManyField(blank=True, related_name='elective_subjects', to='accounts.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('elective', 'Elective')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.semester'),
        ),
    ]
