# Generated by Django 5.2.11 on 2026-03-31 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_subject_division_subject_divisions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='programs',
            field=models.ManyToManyField(blank=True, related_name='elective_subjects', to='accounts.program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.program'),
        ),
    ]
