# Generated by Django 5.2.11 on 2026-03-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subject_programs_alter_subject_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='division',
            name='department',
        ),
        migrations.RemoveField(
            model_name='division',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='division',
            name='program',
        ),
        migrations.RemoveField(
            model_name='division',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.RemoveField(
            model_name='program',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='program',
        ),
    ]
