# Generated by Django 5.2.11 on 2026-03-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deduplicate_and_prepopulate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProgramSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_semester_pairs', to='accounts.subject')),
            ],
            options={
                'ordering': ['program__name', 'semester__name'],
                'unique_together': {('subject', 'program', 'semester')},
            },
        ),
    ]
