# Generated by Django 5.2.11 on 2026-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_faculty_faculty_code_subject_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company or client name, e.g. 'ABC Corp'", max_length=200)),
                ('api_key', models.CharField(editable=False, help_text='Auto-generated API key (shown once on creation)', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to revoke access without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this client')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core'), ('elective', 'Elective')], default='core', max_length=20),
        ),
    ]
